name: Main

on:
  push:

jobs:

  red_amber_green_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: cyber-dojo-start-points/pinned-checkout@main

      - name: Build Language-Start-Point image, test it
        run: ./run_tests.sh