name: Main

on:
  push:

jobs:

  red_amber_green_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build Language-Start-Point image, test it
        run: ./run_tests.sh